### ISSUE TITLE
Duplicate symbol _OBJC_CLASS_$_CardIOCreditCardInfo

### ISSUE THREAD

**Issue by betzerra** [braintree/braintree_ios#53]
Just got this error after updating from 2.x to 3.3.1 
Are you guys using Card.io inside Braintree?

![screen shot 2014-10-08 at 11 36 46](https://cloud.githubusercontent.com/assets/681600/4561013/7e34fda8-4ef9-11e4-98da-0b78bc81edd1.png)

**Comment by Femina** [comment]
I am using Braintree 3.7.0 ... Also , I have #import "CardIO.h" in my viewcontroller. I am getting conflict ...  I didn't use separate pod for CardIO as it included already! How do I need to use or import cardIO ? I am getting file not found!

**Comment by mickeyreiss** [comment]
@femina CardIO is [no longer included in Braintree iOS](https://github.com/braintree/braintree_ios/blob/master/CHANGELOG.md). Please add `pod `CardIO"` to your Podfile.

**Comment by Femina** [comment]
@mickeyreiss Yeah Mickey! I tried pod "CardIO" , but getting conflict between Bolts and CardIO. But keep on getting this issue: http://stackoverflow.com/questions/26794422/need-help-in-xcode-library-not-found-lpods-bolts-exit-code-1. Now I just added SDK instead of CardIO pod and proceeded. It worked! Any clue ?

**Comment by mickeyreiss** [comment]
It could be a number of things. I would need to see the error as well as your Podfile, Podfile.lock and project.pbxproj to know for sure.
