### ISSUE TITLE
Failed to compile bundle on CardinalMobile.armv7.xar using AppCenter w/ CocoaPods

### ISSUE THREAD

**Issue by bull-xu** [braintree/braintree_ios#467]
### General information

* SDK/Library version: 4.25.1
* Environment: Sandbox (Using AppCenter build)
* iOS Version and Device: Xcode 10.2.1, Deployment target iOS 10.0, AppCenter Build
* Integration type and version: CocoaPods 1.7.4

### Issue description

The AppCenter build failed to the latest version 4.25.1. Issue found from 4.25.0.

Logs:

```


    "/Applications/Xcode_10.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" "-arch" "armv7" "-dylib" "-compatibility_version" "1.0.0" "-current_version" "1.0.0.0.0" "-install_name" "@rpath/CardinalMobile.framework/CardinalMobile" "-ios_version_min" "9.0.0" "-rpath" "@executable_path/Frameworks" "-rpath" "@loader_path/Frameworks" "-dead_strip" "-exported_symbols_list" "exports.exp" "-syslibroot" "/Applications/Xcode_10.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk" "-sdk_version" "12.2.0" "-filelist" "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/CardinalMobile5Mk4co/CardinalMobile.armv7.out.LinkFileList" "-ignore_auto_link" "-allow_dead_duplicates" "/Applications/Xcode_10.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/System/Library/Frameworks/Foundation.framework/Foundation.tbd" "/Applications/Xcode_10.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr...
    -= Output =-
    Undefined symbols for architecture armv7:
      "_lprofDirMode", referenced from:
         -exported_symbol[s_list] command line option
      "_lprofCurFilename", referenced from:
         -exported_symbol[s_list] command line option
      "___llvm_profile_raw_version", referenced from:
         -exported_symbol[s_list] command line option
      "_lprofMergeValueProfData", referenced from:
         -exported_symbol[s_list] command line option
      "___llvm_profile_filename", referenced from:
         -exported_symbol[s_list] command line option
      "___llvm_profile_runtime", referenced from:
          __hidden#3_ in 01.o
          __hidden#3_ in 02.o
          __hidden#3_ in 03.o
          __hidden#3_ in 04.o
          __hidden#3_ in 05.o
          __hidden#3_ in 06.o
          __hidden#3_ in 07.o
          ...
    ld: symbol(s) not found for architecture armv7
    Exited with 1
    
    
    error: Failed to compile bundle: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/CardinalMobile5Mk4co/CardinalMobile.armv7.xar
    

Stderr:

>
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:246:in `run'
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:2469:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:2408:in `each'
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:2408:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:2632:in `ProcessIPA'
    /Applications/Xcode_10.2.1.app/Contents/Developer/usr/bin/ipatool:3459:in `<main>'}

** EXPORT FAILED **

##[error]Error: /usr/bin/xcodebuild failed with return code: 70

```

**Comment by sestevens** [comment]
Hi @bull-xu, thanks for opening a new issue. Are you able to reproduce this issue in Xcode? If so, please let us know what steps you took to reproduce. 

Unfortunately, if this issue is only occurring in AppCenter, we may not be able to help troubleshoot. In that case, you may want to reach out to [AppCenter Support](https://docs.microsoft.com/en-us/appcenter/general/support-center#contact-us).

**Comment by ejensen** [comment]
@sestevens  I'm seeing a similar issue since updating to v4.25.0. This during an archive build with Xcode
```
-= Output =-
Undefined symbols for architecture arm64:
"_lprofDirMode", referenced from:
-exported_symbol[s_list] command line option
"_lprofCurFilename", referenced from:
-exported_symbol[s_list] command line option
"___llvm_profile_raw_version", referenced from:
-exported_symbol[s_list] command line option
"_lprofMergeValueProfData", referenced from:
-exported_symbol[s_list] command line option
"___llvm_profile_filename", referenced from:
-exported_symbol[s_list] command line option
"___llvm_profile_runtime", referenced from:
__hidden#3_ in 01.o
__hidden#3_ in 02.o
__hidden#3_ in 03.o
__hidden#3_ in 04.o
__hidden#3_ in 05.o
__hidden#3_ in 06.o
__hidden#3_ in 07.o
...
ld: symbol(s) not found for architecture arm64
Exited with 1
error: Failed to compile bundle: /var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/CardinalMobilePwpzBd/CardinalMobile.arm64.xar
```

**Comment by daliadanila** [comment]
Hi guys,

We're having the same issue. Any updates on it? Thanks

**Comment by sestevens** [comment]
@ejensen @daliadanila Thanks for letting us know! We're looking into the issue.

**Comment by florinvasilevilsan** [comment]
I have managed to get this working. It seems related to this v4.2.5 changes. I have downgraded this v4.2.4 and it worked.

What exactly caused the issue within that particular version? I don't know, nor had time to investigate.

**Comment by sestevens** [comment]
**UPDATE**: We've reproduced this on version 4.25.0 and above. It seems to be an issue with the latest CardinalMobile framework. We've reached out to Cardinal for support, and we'll update here once we have more information.

**Comment by gauravrocks** [comment]
We are noticing the same issue with version 4.24.0. can you please confirm?

**Comment by sestevens** [comment]
Hi @gauravrocks. I wasn't able to reproduce the issue on 4.24.0. Are you getting the exact same error mentioned in the initial comment above?

**Comment by gauravrocks** [comment]
@sestevens YES!
dyld: Library not loaded: @rpath/CardinalMobile.framework/CardinalMobile
Reason: image not found

**Comment by scannillo** [comment]
@gauravrocks, are you integrating with Carthage? It requires an extra step to [add the CardinalMobile.framework to your project.](https://developers.braintreepayments.com/guides/3d-secure/migration/ios/v4#additional-setup-for-carthage). 

This looks unrelated to the AppCenter issue above. Feel free to open a new issue if you think there is a separate error with the SDK, or reach out to Braintree support for guidance on your specific integration https://help.braintreepayments.com/.

**Comment by sestevens** [comment]
**UPDATE**: Version 4.26.1 resolves this issue.

**Comment by daliadanila** [comment]
> **UPDATE**: Version 4.26.1 resolves this issue.

The new version fixed it for us 👍 thanks, guys.

**Comment by sebastianludwig** [comment]
@sestevens we're facing the same issue on a different project. Can you elaborate on _how_ the problem got solved? 😇 Any pointers would be highly appreciated!

**Comment by scannillo** [comment]
@sebastianludwig please see our Release notes for details on the change made in 4.26.1 (https://github.com/braintree/braintree_ios/releases/tag/4.26.1).
